
version: "2"
services:
    ytdl_material:
        build: .
        environment: 
            write_ytdl_config: 'true'
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - ./appdata:/app/config
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:experimental